### ISSUE TITLE
README.md does not provide information about the project

### ISSUE THREAD

**Issue by hackwith** [honeynet/cuckoo-droid#1]
It is clearly visible that the README file doesnt describe anything about this project. Even it contains the travis-CI code : 
`[![Build Status](https://travis-ci.org/cuckoosandbox/cuckoo.png?branch=master)](https://travis-ci.org/cuckoosandbox/cuckoo)`

It would be better if README gives information about what makes [cuckoo-droid](https://github.com/honeynet/cuckoo-droid) different from [cuckoo](https://github.com/cuckoosandbox/cuckoo).

**Comment by jbremer** [comment]
It'll be merged with upstream Cuckoo.
